baseURL: "https://liamvanderpoel.com/"
languageCode: en-us
title: "Liam van der Poel"
theme: Solaria

menu:
  main:
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    - identifier: reference
      name: Reference
      url: /reference/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 30

params:
    defaultTheme: auto
    disableThemeToggle: true
    homeInfoParams:
      Title: Site under construction
      Content: No content for now...
    socialIcons: 
      - name: "github"
        url: "https://github.com/VanderpoelLiam"
    ShowCodeCopyButtons: true